/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesCategoryIndexRouteImport } from './routes/recipes.$category.index'
import { Route as RecipesCategoryRecipeIdRouteImport } from './routes/recipes.$category.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCategoryIndexRoute = RecipesCategoryIndexRouteImport.update({
  id: '/recipes/$category/',
  path: '/recipes/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCategoryRecipeIdRoute = RecipesCategoryRecipeIdRouteImport.update({
  id: '/recipes/$category/$recipeId',
  path: '/recipes/$category/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/$category/$recipeId': typeof RecipesCategoryRecipeIdRoute
  '/recipes/$category/': typeof RecipesCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$category/$recipeId': typeof RecipesCategoryRecipeIdRoute
  '/recipes/$category': typeof RecipesCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/$category/$recipeId': typeof RecipesCategoryRecipeIdRoute
  '/recipes/$category/': typeof RecipesCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/'
    | '/recipes/$category/$recipeId'
    | '/recipes/$category/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes' | '/recipes/$category/$recipeId' | '/recipes/$category'
  id:
    | '__root__'
    | '/'
    | '/recipes/'
    | '/recipes/$category/$recipeId'
    | '/recipes/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesCategoryRecipeIdRoute: typeof RecipesCategoryRecipeIdRoute
  RecipesCategoryIndexRoute: typeof RecipesCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$category/': {
      id: '/recipes/$category/'
      path: '/recipes/$category'
      fullPath: '/recipes/$category/'
      preLoaderRoute: typeof RecipesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$category/$recipeId': {
      id: '/recipes/$category/$recipeId'
      path: '/recipes/$category/$recipeId'
      fullPath: '/recipes/$category/$recipeId'
      preLoaderRoute: typeof RecipesCategoryRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesCategoryRecipeIdRoute: RecipesCategoryRecipeIdRoute,
  RecipesCategoryIndexRoute: RecipesCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
